version: '3'

services:
  web:
    container_name: 'mp_back'
    build: .
    restart: on-failure
    command: bash -c "python manage.py createsuperuser --noinput --username ${DJANGO_SUPERUSER_USERNAME} --email ${DJANGO_SUPERUSER_EMAIL} && python3 manage.py runserver 0.0.0.0:8000" 
    ports:
      - "8000:8000"
    env_file:
      - ./.env