version: "3"

services:
  nginx:
    image: "nginx"
    restart: always
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
      - ./mediafiles:/media
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: django-web-prod
    restart: on-failure
    volumes:
      - .:/code
    command: bash -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"