version: '3'

services:
  web:
    build: .
    restart: on-failure
    volumes:
      - .:/code
    command: bash -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"