# Generated by Django 4.0.2 on 2022-02-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('address', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('image', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MNFT',
            fields=[
                ('address', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('blockchain', models.IntegerField(choices=[(0, 'ETHEREUM'), (1, 'SOLANA'), (2, 'TEZOS'), (3, 'EVERSCALE')], default=0)),
                ('symbol', models.CharField(max_length=300)),
                ('standart', models.IntegerField(choices=[(721, 'ERC721'), (1155, 'ERC1155')], default=721)),
                ('lastUpdate', models.DateField()),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
                ('cost', models.IntegerField(default=0)),
                ('costAd', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnft_creator', to='core.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnft_owner', to='core.user')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnft_lord', to='core.user')),
            ],
        ),
    ]
