# Generated by Django 4.0.2 on 2022-05-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='', max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatarMNFT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='core.mnft'),
        ),
        migrations.AddField(
            model_name='user',
            name='displayName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mnft',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mnft',
            name='costAd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mnft',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnfts_creator', to='core.user'),
        ),
        migrations.AlterField(
            model_name='mnft',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mnft',
            name='lastUpdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mnft',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnfts_owner', to='core.user'),
        ),
        migrations.AlterField(
            model_name='mnft',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mnfts_lord', to='core.user'),
        ),
        migrations.AlterField(
            model_name='mnft',
            name='symbol',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
