# Generated by Django 4.0.2 on 2022-02-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnft',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnfts_creator', to='core.user'),
        ),
        migrations.AlterField(
            model_name='mnft',
            name='lastUpdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mnft',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnfts_owner', to='core.user'),
        ),
        migrations.AlterField(
            model_name='mnft',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnfts_lord', to='core.user'),
        ),
    ]
