# Generated by Django 4.0.2 on 2022-05-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_description_alter_mnft_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnft',
            name='OriginCID',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
