# Generated by Django 4.0.2 on 2022-05-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mnft_origincid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mnftcollection',
            name='symbol',
        ),
        migrations.AddField(
            model_name='blockchain',
            name='symbol',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
