# Generated by Django 4.0.2 on 2022-02-19 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mnft_description_alter_mnft_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnft',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mnfts_lord', to='core.user'),
        ),
    ]
