# Generated by Django 4.0.2 on 2022-02-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mnft_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnft',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mnft',
            name='costAd',
            field=models.FloatField(default=0.0),
        ),
    ]
