# Generated by Django 4.0.2 on 2022-05-29 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mnft_alias_alter_mnftcollection_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnft',
            name='creatorAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_MNFTs', to='core.user'),
        ),
        migrations.AlterField(
            model_name='mnft',
            name='ownerAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_MNFTs', to='core.user'),
        ),
        migrations.AlterField(
            model_name='mnft',
            name='sponsorAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_MNFTs', to='core.user'),
        ),
    ]
